### ISSUE TITLE
Asus N53S

### ISSUE THREAD

**Issue by wathek** [awilliam/asus-switcheroo#1]
I'm running Debian Wheezy 64 Bits with the kernel version 2.6.38-2-amd64
I've compiled asus-switcheroo but I cannot find the folder /sys/kernel/debug/vgaswitcheroo/switch

And when it boots I'm getting Operation Not permitted when it try to load the i915_jprob module.

Thank you for your help

Sincerely
Wathek

**Comment by awilliam** [comment]
Please read the README, module loading order is very important.  If you're trying to load i915-jprobe by hand, you need to use sudo, but to use it correctly, you shouldn't be loading it by hand.  See the README.

**Comment by wathek** [comment]
William,

Thank you for your answer, but I'm using root and the message I'm getting is while it's booting so there's no sudo to do.

**Comment by ghost** [comment]
Same problem here, on Debian wheezy 3.1.0-1-amd64 with an ul30vt. I installed using install-ubuntu, but I get the same error at boot Operation Not permitted when loading i915_jprob

**Comment by ghost** [comment]
I managed to get it working by replacing all the /etc/initramfs-tools/modules by /etc/modules of install-ubuntu in the makefile. Not exactly sure what's the difference, but it's working.
However I tried to put "echo OFF > /sys/kernel/debug/vgaswitcheroo/switch" in /etc/rc.local to switch off the nvidia card at boot but if I do that one of my core is used at 100% continuously and my whole system freeze after 1 key press. If I do it after the system is started it seems to work fine though.
