### ISSUE TITLE
Not compiling on Linux Kernel 3.5

### ISSUE THREAD

**Issue by willysr** [awilliam/asus-switcheroo#16]
I got this error when trying to compile asus-switcheroo on Linux Kernel 3.5
make
make -C /lib/modules/3.5.0-smp/build M=/home/willysr/Hybrid/asus-switcheroo modules
make[1]: Entering directory `/usr/src/linux-3.5'
  CC [M]  /home/willysr/Hybrid/asus-switcheroo/asus-switcheroo.o
/home/willysr/Hybrid/asus-switcheroo/asus-switcheroo.c: In function ‘asus_switcheroo_init’:
/home/willysr/Hybrid/asus-switcheroo/asus-switcheroo.c:320:13: warning: passing argument 2 of ‘vga_switcheroo_register_client’ from incompatible pointer type [enabled by default]
In file included from /home/willysr/Hybrid/asus-switcheroo/asus-switcheroo.c:22:0:
include/linux/vga_switcheroo.h:47:5: note: expected ‘const struct vga_switcheroo_client_ops *’ but argument is of type ‘void (*)(struct pci_dev *, enum vga_switcheroo_state)’
/home/willysr/Hybrid/asus-switcheroo/asus-switcheroo.c:320:13: error: too many arguments to function ‘vga_switcheroo_register_client’
In file included from /home/willysr/Hybrid/asus-switcheroo/asus-switcheroo.c:22:0:
include/linux/vga_switcheroo.h:47:5: note: declared here
make[2]: *** [/home/willysr/Hybrid/asus-switcheroo/asus-switcheroo.o] Error 1
make[1]: *** [_module_/home/willysr/Hybrid/asus-switcheroo] Error 2
make[1]: Leaving directory`/usr/src/linux-3.5'
make: **\* [default] Error 2

**Comment by awilliam** [comment]
Fixed
