### ISSUE TITLE
"disassemble your DSDT" ?

### ISSUE THREAD

**Issue by anpasewi** [awilliam/asus-switcheroo#2]
How do I perform the step called "disassemble your DSDT"? Are there terminal commands I can type? Can you edit that step of the README to make it more n00b-friendly?

**Comment by awilliam** [comment]
# sudo cp /sys/firmware/acpi/tables/DSDT /tmp
 # sudo iasl -d /tmp/DSDT

Or a google search pretty readily turns up other options using acpidump.
