### ISSUE TITLE
Compatibility with Kernel 2.6.38

### ISSUE THREAD

**Issue by Nicias** [awilliam/asus-switcheroo#3]
Thanks for all the great work! I packaged this module for gentoo in the sunrise overlay and it was working great for kernel 2.6.36. However, when I upgraded to 2.6.38 things stopped working. The symptoms are:

1) I don't have a /sys/kernel/debug/vgaswitcheroo anymore.
2) The i915-jprobe module won't load. When I try to load it (as root, before other modules) I get:  "operation not permitted" and dmesg reports "Failed register_jprobe for acpi_lid_notifier_register, -22"

The asus-switcheroo module loads with:

"Found VGA device 0000:00:02.0 (_SB_.PCI0.VGA_): IGD
Found VGA device 0000:01:00.0 (_SB_.PCI0.P0P1.VGA_): DIS
Asus switcheroo: detected DSM switching method _SB_.PCI0.P0P1.VGA_ handle"

in /var/log/messages.

Following the directions for switching to the nvidia card causes a black screen. 

Any suggestions?

**Comment by awilliam** [comment]
I've used the modules on 2.6.38, so I don't think there's any fundamental incompatibility.  The i915_jprobe module not loading should not affect whether you have a vgaswitcheroo file or not.  That should entirely come from the asus-switcheroo module loading and doing so before nouveau loads.  Double check that nouveau is blacklisted and only getting registered after asus-switcheroo.  For the i915-jprobe error, do you have acpi_lid_notifier_register in /proc/kallsyms?

**Comment by Nicias** [comment]
I just tested this, loading asus-switcheroo before any other modules. I get the same thing as above in dmesg, but still no vgaswitcheroo file.

**Comment by Nicias** [comment]
Also, I just checked for that line in the /proc/kallsyms:

 grep acpi_lid_notifier_register kallsyms 
ffffffff812f17a9 T acpi_lid_notifier_register
ffffffff81691770 r __ksymtab_acpi_lid_notifier_register
ffffffff816ab40e r __kstrtab_acpi_lid_notifier_register

That is without i915-jprobe being loaded.

**Comment by nstadigs** [comment]
I can second this issue
I have a fresh install of the latest ubuntu

**Comment by Nicias** [comment]
Perhaps you (awilliam) could post a working .config for 2.6.38?

**Comment by awilliam** [comment]
Works for me on stock Fedora 2.6.38.  Can someone post a dmesg?  My guess is nouveau isn't loading correctly from the initrd.  I've found that blacklisting nouveau and loading it from an init script later often works more reliably.

**Comment by Nicias** [comment]
I'll post a dmesg when I get back to my laptop tonight. However, I think I posted the relevant parts. I'm not using an initrd, and I don't get that debug file, ever before the nvidia driver loads.

**Comment by Nicias** [comment]
here is my dmesg:

http://paste.pocoo.org/show/450885/

Sorry that I keep closing the issue by accident.

**Comment by awilliam** [comment]
I don't see nouveau loading, are you using the dummy_client option?  In order to get the debugfs switcheroo file you need 2 clients and 1 handler.  i915 should be registering a handler.  asus/byo-switcheroo registers a handler.  The nouveau driver typically registers the other client or asus/byo-switcher if you use the dummy_client option.  If asus-switcheroo were using the dummy client option, I would expect to see "vga_switcheroo: enabled" in your dmesg.

**Comment by Nicias** [comment]
I'm using the dummy client option. The module is loaded with dummy_client=1.

**Comment by awilliam** [comment]
Let's make sure the dummy_client option is actually getting set.  Check

 # cat /sys/module/asus_switcheroo/parameters/dummy_client

It should return Y or N.

**Comment by Nicias** [comment]
It returns Y

**Comment by awilliam** [comment]
Good.  If you switch to byo-switcheroo with dummy_client=1 model=AsusUL30VT it will be equivalent to asus-switcheroo, but print whether the registration of the client succeeded.  Your config does include CONFIG_VGA_SWITCHEROO=y, right?

**Comment by Nicias** [comment]
Ahhh, that fixed it. I had that turned off since I thought it would conflict with theses modules. Now it works! Thanks.
