### ISSUE TITLE
/sys/kernel/debug/vgaswitcheroo directory gone missing after installing asus-switcheroo 

### ISSUE THREAD

**Issue by kurosch** [awilliam/asus-switcheroo#5]
Hey guys,

I was installing asus-switcheroo on my asus ul30vt with ubuntu natty (2.6.38-11-generic) unfortunately the /sys/kernel/debug/vgaswitcheroo directory disappears as soon as I reboot after the install.

Update: it seams to me to be a bug that the module sometimes does not load. I did a fresh install and it seams solved till now

Update 30.8.2011
when turning off the laptop with only nvidia enabled the directory goes missing. could some one confirm it whether it happens to them to would be nice to find out for the general public

**Comment by lundquistlab** [comment]
Hey kurosch,

I have had the same problem, I need to do a fresh install every time. I also sometimes lose the picture on my laptop screen after restarting X BUT the picture is fine on any external monitor (HDMI or VGA). I am running natty on a ul50vt. 

Have you happened to find a solution?

**Comment by kurosch** [comment]
it seams that mounting debug in fstab like written in the readme helps a little bit but i have the feeling when shutting down with nvidia enabled and intel disabled it errors on next restart, aswell as when using windows, between reboots(if applicable).
also kernel 3.0 does not seem to be that friendly if it comes down to loading the debug directory.

hope that helps slightly however you should maybe also check whether the kernel was compiled with vga switcheroo enabled.

**Comment by lundquistlab** [comment]
I noticed that I can get it to work if I open terminal and run modprobe -r nouveau then modprobe nouveau (sort of like what is explained here http://linux-hybrid-graphics.blogspot.com/2011/04/linux-nouveau-intelnvidia-working-with.html) I am not sure why that works. 

Thanks for the help.

**Comment by kurosch** [comment]
thanks for the comment running:

   $ sudo modprobe -r nouveau
   $ sudo modprobe nouveau

solves the problem of missing directory.
