### ISSUE TITLE
Support for PEGP/DSM machines?

### ISSUE THREAD

**Issue by starks** [awilliam/asus-switcheroo#9]
`[  366.976381] Found VGA device 0000:00:02.0 (\_SB_.PCI0.GFX0): IGD
[  366.976390] Found VGA device 0000:01:00.0 (\_SB_.PCI0.PEG0.PEGP): DIS
[  366.976404] BYO-switcheroo handler registered`

Not sure how to use this.

Here's my DSDT and SSDTs: http://www.mediafire.com/download.php?rsr5248zl3k3hux

**Comment by awilliam** [comment]
Send a patch or byo switcheroo script if you get it working.

**Comment by starks** [comment]
If I could make sense of my machine's ACPI calls, I would.

As thing stand, I can't even get re-enabling the card to work properly.

The only DSM call I know for my machine seems to be this:
_DSM {0xF8,0xD8,0x86,0xA4,0xDA,0x0B,0x1B,0x47,0xA7,0x2B,0x60,0x42,0xA6,0xB5,0xBE,0xE0} 0x100 0x1A {0x1,0x0,0x0,0x3}
